apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/c0debreaker/k3s-gitops-lab
    targetRevision: HEAD
    path: apps/hello-nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true